export const ADD_PLANTEMPLATES = 'ADD_PLANTEMPLATES';
export const ADD_PLANTEMPLATE = 'ADD_PLANTEMPLATE';
export const PLANTEMPLATE_ERROR = 'PLANTEMPLATE_ERROR';
export const SHOW_PLANTEMPLATE = 'SHOW_PLANTEMPLATE';
export const REMOVE_PLANTEMPLATE = 'REMOVE_PLANTEMPLATE';
