export const ADD_PLAZA_OFFERS = 'ADD_PLAZA_OFFERS';
export const ADD_PLAZA_OFFER = 'ADD_PLAZA_OFFER';
export const PLAZA_OFFER_ERROR = 'PLAZA_OFFER_ERROR';
export const SHOW_PLAZA_OFFER = 'SHOW_PLAZA_OFFER';
export const REMOVE_PLAZA_OFFER = 'REMOVE_PLAZA_OFFER';
